---
#####################################
### Create Groups
#####################################

- name: Add groups to AD
  microsoft.ad.group:
    name: '{{ item.name }}'
    scope: '{{ item.scope }}'
    path: '{{ item.path }}'
    state: present
    protect_from_deletion: true
  with_items: '{{ dc_groups }}'