---
#####################################
### Create Groups
#####################################

- name: Add groups to AD
  community.windows.win_domain_group:
    name: '{{ item.name }}'
    scope: '{{ item.scope }}'
    path: '{{ item.path }}'
    state: present
    protected: true
  with_items: '{{ dc_groups }}'