---
#####################################
### Create Groups
#####################################

- name: Ensure group is present
  community.windows.win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    path: "{{ item.path }}"
  with_items: "{{ groups }}"