---
#####################################
### Create Groups
#####################################

- name: Ensure OU is present & protected    
  community.windows.win_domain_group:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    path: "{{ item.path }}"
    state: present
    protected: true
  with_items: "{{ groups }}"