---
#####################################
### Create Groups
#####################################

- name: test-one
  debug: 
    msg: Name is {{ groups.name }}
  with_item: '{{ groups }}'

- name: test-one-point.one
  debug: 
    msg: '{{ groups.name }}'
  with_item: '{{ groups }}'

#- name: Ensure OU is present & protected    
#  community.windows.win_domain_group:
#    name: "{{ item.name }}"
#    scope: "{{ item.scope }}"
#    path: "{{ item.path }}"
#    state: present
#    protected: true
#  with_items: "{{ groups }}"